/**
 * @modett/types — shared types for Modett e-commerce
 *
 * Mirrors DB enums and core entities from packages/db/migrations/0001_initial.sql.
 * Import from here in both apps/web and apps/api to avoid type mismatch bugs.
 *
 * @example
 *   import { CurrencyCode, Order, OrderState } from '@modett/types'
 */

// Enums (PostgreSQL TYPE ... AS ENUM mirrors)
export type {
  AdminRole,
  AdminStatus,
  SessionKind,
  StylingGuideType,
  UnitStatus,
  CartStatus,
  ReservationStatus,
  OrderState,
  PaymentState,
  FulfillmentState,
  ReturnState,
  AddressKind,
  CurrencyCode,
  PromoType,
  PaymentStatus,
  ReturnType,
  ReturnRequestStatus,
  ReviewStatus,
  ReviewMediaType,
  LedgerType,
  TierLevel,
  MessagingChannel,
  OutboxStatus,
  CampaignStatus,
  DeliveryStatus,
  RateType,
} from './enums'

export {
  ADMIN_ROLES,
  ADMIN_STATUSES,
  SESSION_KINDS,
  STYLING_GUIDE_TYPES,
  UNIT_STATUSES,
  CART_STATUSES,
  RESERVATION_STATUSES,
  ORDER_STATES,
  PAYMENT_STATES,
  FULFILLMENT_STATES,
  RETURN_STATES,
  ADDRESS_KINDS,
  CURRENCY_CODES,
  PROMO_TYPES,
  PAYMENT_STATUSES,
  RETURN_TYPES,
  RETURN_REQUEST_STATUSES,
  REVIEW_STATUSES,
  REVIEW_MEDIA_TYPES,
  LEDGER_TYPES,
  TIER_LEVELS,
  MESSAGING_CHANNELS,
  OUTBOX_STATUSES,
  CAMPAIGN_STATUSES,
  DELIVERY_STATUSES,
  RATE_TYPES,
} from './enums'

// Entity interfaces (PostgreSQL table mirrors)
export type {
  ReturnStatus,
  ReturnReason,
  AdminReturnLineItem,
  AdminReturnTimelineEvent,
  AdminReturnRequest,
  AdminReturnListRow,
  AdminReturnDetailPayload,
  AdminReturnsListResponse,
} from './returns'

export type {
  User,
  Admin,
  AdminInvite,
  Session,
  Category,
  Product,
  ProductPrice,
  ProductImage,
  ProductRelation,
  ProductStylingGuide,
  BestsellerListEntry,
  Banner,
  ProductVariant,
  VariantStock,
  InventoryUnit,
  InventoryMovement,
  InventoryReconciliationLog,
  Cart,
  CartItem,
  Reservation,
  ReservationItem,
  ShippingZone,
  ShippingMethod,
  PromoCode,
  Order,
  PromoRedemption,
  OrderItem,
  OrderAddress,
  OrderContact,
  OrderEvent,
  OrderUnitAllocation,
  PaymentIntent,
  PaymentTransaction,
  ReturnRequest,
  ReturnRequestItem,
  ReturnEvent,
  ReviewRequestToken,
  Review,
  ReviewMedia,
  ReviewFlag,
  LoyaltyAccount,
  LoyaltyLedgerEntry,
  LoyaltyRules,
  LoyaltyGrant,
  InboxMessage,
  NotificationPreferences,
  NotificationOutbox,
  EmailDeliveryLog,
  BackInStockSubscription,
  PriceDropSubscription,
  Campaign,
  CampaignDelivery,
  NotifyMeEvent,
  Wishlist,
  SavedAddress,
  SavedPaymentMethod,
  AnalyticsEvent,
  AnalyticsAggregate,
} from './entities'
